# Generated by Django 4.0.3 on 2022-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('lte_exists', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
    ]
